### ISSUE TITLE
Incorrect behaviour of the only function

### ISSUE THREAD

**Issue by tomek7667** [mobaradev/UnifiedRandom#1]
When setting up the minimum value to `2.5` and maximum value `10`, there is a chance to get values: `[0, 1, 2]` which is not correct. I assume other implementations have a similar bug.
![image](https://user-images.githubusercontent.com/38402753/220996442-6e1dc8f5-6a9a-4fda-8230-c09cc41a911b.png)

**Comment by mobaradev** [comment]
Fixed in 1.01.
Thank you for reporting.
